services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale-gatus
    hostname: ${SERVICE_NAME}
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--advertise-tags=${TS_TAG}
      - TS_DEBUG_MTU=1200
      - TS_DEBUG_ENABLE_PMTUD=1
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:41234
    volumes:
      - ${PWD}/tailscale/config:/config
      - ${PWD}/tailscale/ts/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always

  mcstatus-api:
    build:
      context: ./mcstatus-api
    container_name: mcstatus-api
    restart: unless-stopped

  gatus:
    image: twinproduction/gatus
    container_name: gatus
    network_mode: service:tailscale
    depends_on:
      tailscale:
        condition: service_healthy
    volumes:
      - ./config:/config
      - ./data:/data
    environment:
      - GATUS_CONFIG_PATH=/config
    env_file:
      - ./.env
    restart: always
